[tool.poetry]
name = "seqia_gen"
version = "0.1.0"
description = ""
authors = ["Javier Vela <javier.vela00@gmail.com>"]
readme = "README.md"
packages = [{include = "seqia_gen", from = "src"}]

[tool.poetry.scripts]
main = "seqia_gen.main:main"

[tool.poetry.dependencies]
python = "^3.12"
langchain = "^0.2.9"
langchain-community = "^0.2.7"
seqia = { path = "./src/seqia", develop = true }
python-dotenv = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.4.4"


[tool.poetry.group.dev.dependencies]
scikit-learn = "^1.5.1"
matplotlib = "^3.9.1"
seaborn = "^0.13.2"
pyqt6 = "^6.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
