[tool.poetry]
name = "ciena_llm"
version = "0.4.1"
description = ""
authors = ["Javier Vela <javier.vela00@gmail.com>"]
readme = "README.md"
packages = [{ include = "ciena_llm", from = "src" }]

[tool.poetry.scripts]
main = "ciena_llm.main:main"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
python-dotenv = "^1.0.1"
spacy = "^3.8.4"
langchain-ollama = "^1.0.1"
pyyaml = "^6.0.2"
transformers = "^4.50.1"
pylint-pydantic = "^0.3.5"

[tool.poetry.group.dev.dependencies]
scikit-learn = "^1.6.1"
matplotlib = "^3.10.1"
seaborn = "^0.13.2"
pandas = "^2.2.3"
ruff = "^0.13.0"
python-dotenv = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
