version: 0.4.0
llm:
  name: "qwen3:8b"
  temperature: 0
  context_length: 32768
  num_predict_tokens: 4096
  structured_output_mode: "tool" # "prompt" or "tool"
  seed: 42

stages:
  summarization:
    enable: True
    steps:
      summarization:
        prompt:
          step: summarization
          language: en
  event_identification:
    enable: False
    steps:
      extraction:
        enable: True
        prompt:
          language: en
          step: extraction
          cot: False
      self_criticism:
        enable: True
        prompt:
          step: self_criticism
          language: en
      response_parsing:
        enable: True
        prompt:
          step: response_parsing
          language: en
  impact_extraction:
    enable: True
    steps:
      extraction:
        enable: True
        prompt:
          language: en
          step: extraction
          category: description
          cot: True
      self_criticism:
        enable: True
        prompt:
          step: self_criticism
          language: en
      response_parsing:
        enable: True
        prompt:
          step: response_parsing
          language: en
  location_extraction: # TODO location or provinces 
    enable: True
    steps:
      extraction:
        enable: True
        prompt:
          language: en
          step: extraction
          category: province
          cot: True
      self_criticism:
        enable: True
        prompt:
          step: self_criticism
          language: en
      response_parsing:
        enable: True
        prompt:
          step: response_parsing
          language: en
  hail_extraction:
    enable: True
    steps:
      extraction:
        enable: True
        prompt:
          language: en
          step: extraction
          cot: False
      self_criticism:
        enable: False
        prompt:
          step: self_criticism
          language: en
      response_parsing:
        enable: True
        prompt:
          step: response_parsing
          language: en
    
# event:
#   tag: "hail"
#   text_es: "granizo"
#   text_en: "hail"
#   description_es: null
#   description_en: null

output:
  summary:
    - article_filename
    - article_hail_event
    - article_date
    - article_url
    - article_headline
