pipeline:
  drought:
    enable: True
    exclude: True
    order: 100
  impact:
    enable: False # TODO WIP
    order: 200
  location:
    enable: True
    order: 300
llm:
  default:
    name: "llama3.1"
    temperature: 0
    # Max: 131072
    context_length: 32768
# llm:
#   default:
#     name: "llama3"
#     temperature: 0
#     context_length: 8192
#   impact_extraction:
#     name: ""
#     temperature: 0.6
#   location_extraction:
#     name: ""
#     temperature: 0.1
#   location_response_parser:
#     name: ""
#     context_length: 1234
prompt:
  drought_extraction: "drought_extraction_es"
  impact_extraction: "impact_extraction_es"
  location_extraction: "location_extraction_es"
  drought_response_parser: "drought_response_parser_en"
  impact_response_parser: "impact_response_parser_en"
  location_response_parser: "location_response_parser_en"
impacts:
  - tag: "agriculture"
    text: "agricultura"
  - tag: "farming"
    text: "ganadería"
  - tag: "hydrological-resources"
    text: "recursos hídricos"
  - tag: "energy"
    text: "energía"
output:
  summary:
    - article_filename
    - article_drought
    - article_impacts_aggregated
    - article_locations_aggregated
    - article_date
    - article_url
    - article_headline
  location_article:
    - article_filename
    - article_body
    - location_name
    - location_type