impacts:
  - "agriculture"
  - "farming"
  - "hidrological_resources"
  - "energy"
  - "other"
output:
  summary:
    - "article_filename"
    - "article_drought"
    - "article_impacts_aggregated"
    - "article_locations_aggregated"
    - "article_locations_aggregated"
    - "article_date"
    - "article_url"
    - "article_headline"