impacts:
  - tag: "agriculture"
    text: "agricultura"
  - tag: "farming"
    text: "ganadería"
  - tag: "hydrological-resources"
    text: "recursos hídricos"
  - tag: "energy"
    text: "energía"
output:
  summary:
    - "article_filename"
    - "article_drought"
    - "article_impacts_aggregated"
    - "article_locations_aggregated"
    - "article_locations_aggregated"
    - "article_date"
    - "article_url"
    - "article_headline"